sudo: required
dist: trusty
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: HvkSDjAVlYflmRnzq4WLYDccK+Ka44NfA7RVnycYmTzpviyjYSt1nSx6bMa/tmWbK+TCzjj6sA/B88Wn1udYe7K6SxZfz4zW1E3kPTgoT3mGuvhpaGfx4Fhbr8N1tXAJ/LCvwFbF5D5tMjMQs1CwCIirtBT8i5f6kqdbDAntA7xSq789yZTdAwgtqEVCOFyNHVKoCQdGmy+7u5rdRHFdTVWcO5k7m6qGeG0L7BOGRQrCBPRfvG+qLrWBJNbxf3jaCiVd760VsmTPXHMjUftDao6X79eXWq+LxG0tZKP+DHxJo88/GIdAP4U2JPupqPua/hKHUkXEn729NtAQsDCnhM3mKbJjc4dTQphR+WVCmNaqoGljjjflQ6M9QgaDqARTq2Vr7sBAgNvf8G5eShklL1k8oQ/4QRCMr6a8AeExvAa9M3rx5Czb3HSwgzf8jDl0g5vd34hiBsTC94GFVZjVGu1c7URcVKV1BWvIaOSHTbJxf4DEpc7+gfOtYy+YN+zS2Wc18TlxoD3NHcAjFVkAY+K4v6QaTmkqQsWmP1N/B0ySTQf3UhoXnyifm22alYMnTzvJgN3IlQ6kht4YeLTCRBZwAjs5p93ymUs6BjTJasB/x3MytsWoXYk2O1LuSitk+kvjEy5ogDixhBeLXZeKlmYhMPNcSz+RqGCqbClTzpI=
  - secure: uoedx5n7VAfe4o4aRsPtb+BhSArMcfDPy0E+gY9yGBR/qprmck6cyvBAiWUUEehDfhyWKupXk0pWIIQSo7/BfK6SOzwutfBHsIKiJmSP8KYEjT4rpW03Vhd4dkExU8Qg5Er1R878/PunF7XJq51cXfnfcS0lpzwwh6o+qsFoPgs3yRcDZCVVg60MxetQ/5Ob4Pf1ew26MHwqDzT7N0nETkp8EljNe8+RZYMqEeX3FD4oJDli072NJ+0hYOpCt8LfMQecZ/cR+vLdW/nWeqzuXPBp5TkmIqB/MVUG8yVQv6y77Fh3RGuo7ch2gJcVJCMpkmI0zhBtk6Up8Y//wCUBcdXabnO2AOlCnOphBfhFrCd0/lc3OrUDE1vsvwm/mT2rSGpNRXcXD0cpP33RQ2s/stlYkoDOM9sb9S/CGxqRHB8jdrvfU47aee1IYV8vZgr+I0NefK1uNGBk9n+WXNF+d8svpQ1hgTArED7MG4NO1+rUYgKcftCQzmO3RSzC3MOyuH7kq+eTnMU3InEEByzUPBGIStndmv11wIGGh/qCUuVivPTnn6JsR6FEBfF0ADuOSB3Z8RZMBhv1kOBKCv3xsWG6et/ASRFte/eZu0v1AN3LaiZEsfCJ22TNwGaqwmYAzHrpqYf/FViUlGmJCUuJfC9/EWm3fF09o2BqyDu7ZTk=
  - secure: J1VASH7P9W0BUI5EoDfM58XhSxGcyJeg0mtP7g4a5aLIGar0raOgmqIfVSEf2DgtwXVWnLDlR6c//aaw/k2oQ49gZPDy9YVr+zNkTuMffkcVDpNeqmMXfd+um4siUxiTHsX834a0FfPkV/sRyvRgiAJGDdGm+mHSbkXygTb6MY+SvmRs7SfjURw+nqszjfN/gniIQr4l6CrmTHirzl5HDtRu6mWlXXin+/gSJL+giowJl6o2nbj8NWehQrkSHeYjILQ+sgkDfD1cnXp43cK5ynuTv8ugdQXN63wcA8MaS+pf5gfOqwOe4VioQ8vToOsG2Ladl+Oqs9HJjkNs3k75mEk5dwy0rbU0edjOY6p7CpqRdCBfFik9s+B9dWTsSNcI6ocGJ/5TzqwuvfT7UhsJ81faFpLj0jSriMX07djeKBzMx4rPLrQv+JhZPN83zEoF+aNsLrzghuTqxAE2Qp2MLfqY6L8khWeyUnuqp+PBiyOPCOqJrhqJIcSQCRIDC/WZN07I7tpZ6fVqgU48bPDu9RG5uS7N0e3dSXMpgFrAidRdKDgg1WKJtTrxCz9Y3ZN7L8DJPUUbCJYzsqM9xXTG1gBgkbTK+5S1iFH55qJ/DQvzqqSZu/oC0pJTImCNNI2GMAKr/RZPcmcaAoy/zykic/Zf6z9e5a4aof1f+aT+nTg=
