sudo: required
dist: xenial
addons:
  chrome: stable
  firefox: latest
language: node_js
services:
- xvfb
node_js:
- '8'
cache:
  yarn: true
branches:
  except:
  - stable
before_install:
- export START_TIME=$( date +%s )
- npm i -g yarn
install:
- yarn add @ckeditor/ckeditor5-dev-tests
- ckeditor5-dev-tests-install-dependencies
script:
- ckeditor5-dev-tests-travis
after_success:
- ckeditor5-dev-tests-save-revision
after_script:
- export END_TIME=$( date +%s )
- ckeditor5-dev-tests-notify-travis-status
env:
  global:
  - secure: e17Hx4+i5aohCbN4if6jp1wwbrlQZJk3nRiGrodjLkrIUgruGqyMxwLfS1/s4J9U/KXsMrLn9HxI/nc8aluD7axpPV9V/sNNl4T1muL4sekyyYWOG17cGZudY98N2hkobbgVCwpId4qeatZlqQz89YNqKEqJTtJTFjzn3WcT/NG+z6V0SfIT0LMKRFsrssMBNy+zw6Q+l0T++PG+9Y2AebkHAAAHKT3U2dXS5IAGs8FtLmyuxAVS83PqLfeX99zM37VCXno3smeH1a6pI8LqtTeLeue2nx0Er0zw9V7ex21xWGOy4Z/Z/RgbGU65JmyLqZhJPfCmhk59h6dCWcuYjxBGewqa5ZSocCFLQaILOHO4mW0vOnOjRenkTlV31BIkO1/YTHExC4XUFLzhFTXDGqLpOjf3xH6PqK5ZeFFmDCUC4DhM7wcuWco/PtXl94YM4LtOGZfmV56MvdiY9WW5IG3bEDDIt+30NZryziYlRg+DwNUTxy5w0ZHl1yw+8fzPIld7eq563Fy8Un4UG9PP+2VDcbafcfDfiMoAY4tLBF2U5/8R1cBVZHs+NDghdtGF58SNyw4bzbP/2jYbw+woQ2P5th/zFhBtwZUCaikuGy5tXRu/6NjRfF2BpSYO6JY0o7vXcZXyNGvUai44Pr1+GGwU5EFX0vc3T0o2tR4GOmA=
